apiVersion: apps/v1
kind: Deployment
metadata:
  name: versefind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: versefind
  template:
    metadata:
      name: versefind
      labels:
        app: versefind
    spec:
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        env:
        - name: discovery.type
          value: single-node
        volumeMounts:
        - name: appdata
          mountPath: /usr/share/elasticsearch/data
      - name: api
        image: registry.svc.vesey.tech/will/versefind/api
        env:
        - name: OAUTH_CLIENTID
          valueFrom:
            secretKeyRef:
              name: versefind
              key: OAUTH_CLIENTID
        - name: OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: versefind
              key: OAUTH_SECRET
      - name: web
        image: registry.svc.vesey.tech/will/versefind/web
      volumes:
      - name: appdata
        nfs:
          server: nas
          path: /mnt/tank/data/containers/versefind
      imagePullSecrets:
      - name: gitlab-registry


---
apiVersion: v1
kind: Service
metadata:
  name: versefind
spec:
  ports:
  - name: tcp
    port: 3000
  selector:
    app: versefind

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: versefind
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`versefind.vesey.tech`)
    kind: Rule
    services:
    - name: versefind
      port: 3000
  tls:
    certResolver: default
    domains:
    - main: "versefind.vesey.tech"

